###################################################################

# Created by write_sdc on Mon May 4 21:09:27 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_fanout 100 [current_design]
group_path -name FEEDTHROUGH  -from [list [get_ports mclk] [get_ports puc_rst] [get_ports {pmem_dout[15]}] [get_ports {pmem_dout[14]}] [get_ports {pmem_dout[13]}] [get_ports {pmem_dout[12]}] [get_ports {pmem_dout[11]}] [get_ports {pmem_dout[10]}] [get_ports {pmem_dout[9]}] [get_ports {pmem_dout[8]}] [get_ports {pmem_dout[7]}] [get_ports {pmem_dout[6]}] [get_ports {pmem_dout[5]}] [get_ports {pmem_dout[4]}] [get_ports {pmem_dout[3]}] [get_ports {pmem_dout[2]}] [get_ports {pmem_dout[1]}] [get_ports {pmem_dout[0]}] [get_ports {dmem_dout[15]}] [get_ports {dmem_dout[14]}] [get_ports {dmem_dout[13]}] [get_ports {dmem_dout[12]}] [get_ports {dmem_dout[11]}] [get_ports {dmem_dout[10]}] [get_ports {dmem_dout[9]}] [get_ports {dmem_dout[8]}] [get_ports {dmem_dout[7]}] [get_ports {dmem_dout[6]}] [get_ports {dmem_dout[5]}] [get_ports {dmem_dout[4]}] [get_ports {dmem_dout[3]}] [get_ports {dmem_dout[2]}] [get_ports {dmem_dout[1]}] [get_ports {dmem_dout[0]}]]  -to [list [get_ports {pmem_addr[14]}] [get_ports {pmem_addr[13]}] [get_ports {pmem_addr[12]}] [get_ports {pmem_addr[11]}] [get_ports {pmem_addr[10]}] [get_ports {pmem_addr[9]}] [get_ports {pmem_addr[8]}] [get_ports {pmem_addr[7]}] [get_ports {pmem_addr[6]}] [get_ports {pmem_addr[5]}] [get_ports {pmem_addr[4]}] [get_ports {pmem_addr[3]}] [get_ports {pmem_addr[2]}] [get_ports {pmem_addr[1]}] [get_ports {pmem_addr[0]}] [get_ports pmem_en] [get_ports {dmem_addr[15]}] [get_ports {dmem_addr[14]}] [get_ports {dmem_addr[13]}] [get_ports {dmem_addr[12]}] [get_ports {dmem_addr[11]}] [get_ports {dmem_addr[10]}] [get_ports {dmem_addr[9]}] [get_ports {dmem_addr[8]}] [get_ports {dmem_addr[7]}] [get_ports {dmem_addr[6]}] [get_ports {dmem_addr[5]}] [get_ports {dmem_addr[4]}] [get_ports {dmem_addr[3]}] [get_ports {dmem_addr[2]}] [get_ports {dmem_addr[1]}] [get_ports {dmem_addr[0]}] [get_ports {dmem_din[15]}] [get_ports {dmem_din[14]}] [get_ports {dmem_din[13]}] [get_ports {dmem_din[12]}] [get_ports {dmem_din[11]}] [get_ports {dmem_din[10]}] [get_ports {dmem_din[9]}] [get_ports {dmem_din[8]}] [get_ports {dmem_din[7]}] [get_ports {dmem_din[6]}] [get_ports {dmem_din[5]}] [get_ports {dmem_din[4]}] [get_ports {dmem_din[3]}] [get_ports {dmem_din[2]}] [get_ports {dmem_din[1]}] [get_ports {dmem_din[0]}] [get_ports {dmem_wen[1]}] [get_ports {dmem_wen[0]}] [get_ports dmem_en]]
group_path -name REGIN  -from [list [get_ports mclk] [get_ports puc_rst] [get_ports {pmem_dout[15]}] [get_ports {pmem_dout[14]}] [get_ports {pmem_dout[13]}] [get_ports {pmem_dout[12]}] [get_ports {pmem_dout[11]}] [get_ports {pmem_dout[10]}] [get_ports {pmem_dout[9]}] [get_ports {pmem_dout[8]}] [get_ports {pmem_dout[7]}] [get_ports {pmem_dout[6]}] [get_ports {pmem_dout[5]}] [get_ports {pmem_dout[4]}] [get_ports {pmem_dout[3]}] [get_ports {pmem_dout[2]}] [get_ports {pmem_dout[1]}] [get_ports {pmem_dout[0]}] [get_ports {dmem_dout[15]}] [get_ports {dmem_dout[14]}] [get_ports {dmem_dout[13]}] [get_ports {dmem_dout[12]}] [get_ports {dmem_dout[11]}] [get_ports {dmem_dout[10]}] [get_ports {dmem_dout[9]}] [get_ports {dmem_dout[8]}] [get_ports {dmem_dout[7]}] [get_ports {dmem_dout[6]}] [get_ports {dmem_dout[5]}] [get_ports {dmem_dout[4]}] [get_ports {dmem_dout[3]}] [get_ports {dmem_dout[2]}] [get_ports {dmem_dout[1]}] [get_ports {dmem_dout[0]}]]
group_path -name REGOUT  -to [list [get_ports {pmem_addr[14]}] [get_ports {pmem_addr[13]}] [get_ports {pmem_addr[12]}] [get_ports {pmem_addr[11]}] [get_ports {pmem_addr[10]}] [get_ports {pmem_addr[9]}] [get_ports {pmem_addr[8]}] [get_ports {pmem_addr[7]}] [get_ports {pmem_addr[6]}] [get_ports {pmem_addr[5]}] [get_ports {pmem_addr[4]}] [get_ports {pmem_addr[3]}] [get_ports {pmem_addr[2]}] [get_ports {pmem_addr[1]}] [get_ports {pmem_addr[0]}] [get_ports pmem_en] [get_ports {dmem_addr[15]}] [get_ports {dmem_addr[14]}] [get_ports {dmem_addr[13]}] [get_ports {dmem_addr[12]}] [get_ports {dmem_addr[11]}] [get_ports {dmem_addr[10]}] [get_ports {dmem_addr[9]}] [get_ports {dmem_addr[8]}] [get_ports {dmem_addr[7]}] [get_ports {dmem_addr[6]}] [get_ports {dmem_addr[5]}] [get_ports {dmem_addr[4]}] [get_ports {dmem_addr[3]}] [get_ports {dmem_addr[2]}] [get_ports {dmem_addr[1]}] [get_ports {dmem_addr[0]}] [get_ports {dmem_din[15]}] [get_ports {dmem_din[14]}] [get_ports {dmem_din[13]}] [get_ports {dmem_din[12]}] [get_ports {dmem_din[11]}] [get_ports {dmem_din[10]}] [get_ports {dmem_din[9]}] [get_ports {dmem_din[8]}] [get_ports {dmem_din[7]}] [get_ports {dmem_din[6]}] [get_ports {dmem_din[5]}] [get_ports {dmem_din[4]}] [get_ports {dmem_din[3]}] [get_ports {dmem_din[2]}] [get_ports {dmem_din[1]}] [get_ports {dmem_din[0]}] [get_ports {dmem_wen[1]}] [get_ports {dmem_wen[0]}] [get_ports dmem_en]]
