###################################################################

# Created by write_sdc on Tue Jun 2 14:46:49 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_fanout 100 [current_design]
set_load -pin_load 0.005 [get_ports {alu_out[15]}]
set_load -pin_load 0.005 [get_ports {alu_out[14]}]
set_load -pin_load 0.005 [get_ports {alu_out[13]}]
set_load -pin_load 0.005 [get_ports {alu_out[12]}]
set_load -pin_load 0.005 [get_ports {alu_out[11]}]
set_load -pin_load 0.005 [get_ports {alu_out[10]}]
set_load -pin_load 0.005 [get_ports {alu_out[9]}]
set_load -pin_load 0.005 [get_ports {alu_out[8]}]
set_load -pin_load 0.005 [get_ports {alu_out[7]}]
set_load -pin_load 0.005 [get_ports {alu_out[6]}]
set_load -pin_load 0.005 [get_ports {alu_out[5]}]
set_load -pin_load 0.005 [get_ports {alu_out[4]}]
set_load -pin_load 0.005 [get_ports {alu_out[3]}]
set_load -pin_load 0.005 [get_ports {alu_out[2]}]
set_load -pin_load 0.005 [get_ports {alu_out[1]}]
set_load -pin_load 0.005 [get_ports {alu_out[0]}]
set_load -pin_load 0.005 [get_ports {alu_stat[3]}]
set_load -pin_load 0.005 [get_ports {alu_stat[2]}]
set_load -pin_load 0.005 [get_ports {alu_stat[1]}]
set_load -pin_load 0.005 [get_ports {alu_stat[0]}]
create_clock -name v_clk  -period 10  -waveform {0 1}
set_clock_uncertainty 0.2  [get_clocks v_clk]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[15]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[14]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[13]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[12]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[11]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[10]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[9]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[8]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[7]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[6]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[5]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[4]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[3]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[2]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[1]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_src[0]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[15]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[14]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[13]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[12]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[11]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[10]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[9]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[8]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[7]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[6]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[5]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[4]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[3]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[2]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[1]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {op_dst[0]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[13]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[12]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[11]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[10]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[9]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[8]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[7]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[6]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[5]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[4]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[3]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[2]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[1]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {inst_alu[0]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports inst_bw]
set_input_delay -clock v_clk  -max 0.2  [get_ports {status[3]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {status[2]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {status[1]}]
set_input_delay -clock v_clk  -max 0.2  [get_ports {status[0]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[15]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[14]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[13]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[12]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[11]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[10]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[9]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[8]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[7]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[6]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[5]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[4]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[3]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[2]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[1]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_out[0]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_stat[3]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_stat[2]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_stat[1]}]
set_output_delay -clock v_clk  -max 0.2  [get_ports {alu_stat[0]}]
set_input_transition -max 0.1  [get_ports {inst_alu[13]}]
set_input_transition -min 0.1  [get_ports {inst_alu[13]}]
set_input_transition -max 0.1  [get_ports {inst_alu[12]}]
set_input_transition -min 0.1  [get_ports {inst_alu[12]}]
set_input_transition -max 0.1  [get_ports {inst_alu[11]}]
set_input_transition -min 0.1  [get_ports {inst_alu[11]}]
set_input_transition -max 0.1  [get_ports {inst_alu[10]}]
set_input_transition -min 0.1  [get_ports {inst_alu[10]}]
set_input_transition -max 0.1  [get_ports {inst_alu[9]}]
set_input_transition -min 0.1  [get_ports {inst_alu[9]}]
set_input_transition -max 0.1  [get_ports {inst_alu[8]}]
set_input_transition -min 0.1  [get_ports {inst_alu[8]}]
set_input_transition -max 0.1  [get_ports {inst_alu[7]}]
set_input_transition -min 0.1  [get_ports {inst_alu[7]}]
set_input_transition -max 0.1  [get_ports {inst_alu[6]}]
set_input_transition -min 0.1  [get_ports {inst_alu[6]}]
set_input_transition -max 0.1  [get_ports {inst_alu[5]}]
set_input_transition -min 0.1  [get_ports {inst_alu[5]}]
set_input_transition -max 0.1  [get_ports {inst_alu[4]}]
set_input_transition -min 0.1  [get_ports {inst_alu[4]}]
set_input_transition -max 0.1  [get_ports {inst_alu[3]}]
set_input_transition -min 0.1  [get_ports {inst_alu[3]}]
set_input_transition -max 0.1  [get_ports {inst_alu[2]}]
set_input_transition -min 0.1  [get_ports {inst_alu[2]}]
set_input_transition -max 0.1  [get_ports {inst_alu[1]}]
set_input_transition -min 0.1  [get_ports {inst_alu[1]}]
set_input_transition -max 0.1  [get_ports {inst_alu[0]}]
set_input_transition -min 0.1  [get_ports {inst_alu[0]}]
set_input_transition -max 0.1  [get_ports {op_dst[15]}]
set_input_transition -min 0.1  [get_ports {op_dst[15]}]
set_input_transition -max 0.1  [get_ports {op_dst[14]}]
set_input_transition -min 0.1  [get_ports {op_dst[14]}]
set_input_transition -max 0.1  [get_ports {op_dst[13]}]
set_input_transition -min 0.1  [get_ports {op_dst[13]}]
set_input_transition -max 0.1  [get_ports {op_dst[12]}]
set_input_transition -min 0.1  [get_ports {op_dst[12]}]
set_input_transition -max 0.1  [get_ports {op_dst[11]}]
set_input_transition -min 0.1  [get_ports {op_dst[11]}]
set_input_transition -max 0.1  [get_ports {op_dst[10]}]
set_input_transition -min 0.1  [get_ports {op_dst[10]}]
set_input_transition -max 0.1  [get_ports {op_dst[9]}]
set_input_transition -min 0.1  [get_ports {op_dst[9]}]
set_input_transition -max 0.1  [get_ports {op_dst[8]}]
set_input_transition -min 0.1  [get_ports {op_dst[8]}]
set_input_transition -max 0.1  [get_ports {op_dst[7]}]
set_input_transition -min 0.1  [get_ports {op_dst[7]}]
set_input_transition -max 0.1  [get_ports {op_dst[6]}]
set_input_transition -min 0.1  [get_ports {op_dst[6]}]
set_input_transition -max 0.1  [get_ports {op_dst[5]}]
set_input_transition -min 0.1  [get_ports {op_dst[5]}]
set_input_transition -max 0.1  [get_ports {op_dst[4]}]
set_input_transition -min 0.1  [get_ports {op_dst[4]}]
set_input_transition -max 0.1  [get_ports {op_dst[3]}]
set_input_transition -min 0.1  [get_ports {op_dst[3]}]
set_input_transition -max 0.1  [get_ports {op_dst[2]}]
set_input_transition -min 0.1  [get_ports {op_dst[2]}]
set_input_transition -max 0.1  [get_ports {op_dst[1]}]
set_input_transition -min 0.1  [get_ports {op_dst[1]}]
set_input_transition -max 0.1  [get_ports {op_dst[0]}]
set_input_transition -min 0.1  [get_ports {op_dst[0]}]
set_input_transition -max 0.1  [get_ports {op_src[15]}]
set_input_transition -min 0.1  [get_ports {op_src[15]}]
set_input_transition -max 0.1  [get_ports {op_src[14]}]
set_input_transition -min 0.1  [get_ports {op_src[14]}]
set_input_transition -max 0.1  [get_ports {op_src[13]}]
set_input_transition -min 0.1  [get_ports {op_src[13]}]
set_input_transition -max 0.1  [get_ports {op_src[12]}]
set_input_transition -min 0.1  [get_ports {op_src[12]}]
set_input_transition -max 0.1  [get_ports {op_src[11]}]
set_input_transition -min 0.1  [get_ports {op_src[11]}]
set_input_transition -max 0.1  [get_ports {op_src[10]}]
set_input_transition -min 0.1  [get_ports {op_src[10]}]
set_input_transition -max 0.1  [get_ports {op_src[9]}]
set_input_transition -min 0.1  [get_ports {op_src[9]}]
set_input_transition -max 0.1  [get_ports {op_src[8]}]
set_input_transition -min 0.1  [get_ports {op_src[8]}]
set_input_transition -max 0.1  [get_ports {op_src[7]}]
set_input_transition -min 0.1  [get_ports {op_src[7]}]
set_input_transition -max 0.1  [get_ports {op_src[6]}]
set_input_transition -min 0.1  [get_ports {op_src[6]}]
set_input_transition -max 0.1  [get_ports {op_src[5]}]
set_input_transition -min 0.1  [get_ports {op_src[5]}]
set_input_transition -max 0.1  [get_ports {op_src[4]}]
set_input_transition -min 0.1  [get_ports {op_src[4]}]
set_input_transition -max 0.1  [get_ports {op_src[3]}]
set_input_transition -min 0.1  [get_ports {op_src[3]}]
set_input_transition -max 0.1  [get_ports {op_src[2]}]
set_input_transition -min 0.1  [get_ports {op_src[2]}]
set_input_transition -max 0.1  [get_ports {op_src[1]}]
set_input_transition -min 0.1  [get_ports {op_src[1]}]
set_input_transition -max 0.1  [get_ports {op_src[0]}]
set_input_transition -min 0.1  [get_ports {op_src[0]}]
